version: "3"
services:
  live-app-api:
    build: 
        context: ./api
        dockerfile: Dockerfile.live
    user: root
    ports:
      - "6200:4000"
    restart: always
    volumes:
      - /var/lib/jenkins/workspace/ace_book_live/api:/usr/src/app/acebook_live/api
      - /usr/src/app/acebook_live/api/dist
      - /usr/src/app/acebook_live/api/node_modules

  live-app-file:
      build: 
        context: ./file-srv
        dockerfile: Dockerfile.live
      user: root
      ports:
        - "6302:3002"
      restart: always
      volumes:
        - /var/lib/jenkins/workspace/ace_book_live/file-srv:/usr/src/app/acebook_live/file-srv
        - /mnt/nas/acebook/uploads-live:/usr/src/app/acebook_live/file-srv/public/ftp/uploads
        - /usr/src/app/acebook_live/file-srv/node_modules

  live-app-front:
    build: 
      context: ./front
      dockerfile: Dockerfile.live
    user: root
    privileged: true
    ports:
      - "6100:3000"
    restart: always
    volumes:
      - /var/lib/jenkins/workspace/ace_book_live/front:/usr/src/app/acebook_live/front
      - /mnt/nas/acebook/uploads-live:/usr/src/app/acebook_live/front/public/uploads
      - /usr/src/app/acebook_live/front/node_modules
      - /usr/src/app/acebook_live/front/.next
    depends_on:
      - "live-app-api"
