FROM node:16.13.0-alpine
WORKDIR /usr/src/app/acebook_staging/api
COPY package*.json ./
COPY . .

ENV DATABASE_URL="mongodb://192.168.1.241:27017,192.168.1.242:27017,192.168.1.243:27017/jestoni"
ENV DATABASE_URL_DEV="mongodb://192.168.1.241:27017,192.168.1.242:27017,192.168.1.243:27017/jestoni"
ENV SMS_URL="http://139.135.152.75:8087/cgi/WebCGI?1500101=account=apiuser&password=apipass&port=1"
ENV DATABASE_NAME=jestoni
ENV SYS_ENV=production
ENV FRONT_URL="https://192.168.1.6.nip.io"
# ENV NODE_ENV=production

RUN yarn

RUN yarn build
EXPOSE 6200
# RUN yarn build:gql
# RUN yarn start

CMD ["yarn", "start:prod"]
# CMD ["yarn", "build", "start:prod"]