FROM node:16.13.0-alpine
WORKDIR /usr/src/app/acebook_live/api
COPY package*.json ./
COPY . .

ENV DATABASE_URL="mongodb://172.16.10.105:27017,172.16.10.106:27017,172.16.10.107:27017/acebook-live"
ENV DATABASE_URL_DEV="mongodb://172.16.10.105:27017,172.16.10.106:27017,172.16.10.107:27017/acebook-live"
ENV SMS_URL="http://139.135.152.75:8087/cgi/WebCGI?1500101=account=apiuser&password=apipass&port=1"
ENV DATABASE_NAME=acebook-live
ENV SYS_ENV=production
ENV FRONT_URL="https://acebook.acemcbohol.ph"
# ENV NODE_ENV=production

RUN yarn

RUN yarn build
EXPOSE 6200
# RUN yarn build:gql
# RUN yarn start

CMD ["yarn", "start:prod"]
# CMD ["yarn", "build", "start:prod"]