name: Acebook API LIVE

on: 
  push:
     branches: [ main ]
#     paths:
#       - 'api/**' 
jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node-version: [16.13.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    outputs:
      version: ${{ steps.package-version.outputs.current-version }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: api
  
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: docker build nodejs
      run: |       
       docker build -f api/Dockerfile.beta ./api -t "intjborj/api-demo:${{ steps.package-version.outputs.current-version}}"  --build-arg PROJ_VERSION="${{ steps.package-version.outputs.current-version}}"  
    - name: docker push
      run: |
        docker push intjborj/api-demo:${{ steps.package-version.outputs.current-version}}

  deployment:
    # if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'staging-deployment/')
    environment: main
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout to the ArgoCD repo
        uses: actions/checkout@v2
        with:
          repository: 'intjborj/argocd'
          ref: 'main'
          token: ${{ secrets.PRIVATE_REPO }} 
      # - name: Update ArgoCD Manifest
      #   run: |
      #     cd dev
      #     echo ${{needs.build.outputs.version}}
      #     sed -i 's|intjborj/api-demo:\(.*\)|intjborj/api-demo:${{ needs.build.outputs.version }}|' api-demo.yaml
      #     cat api-demo.yaml
      #     git config --global user.name "api deployment"
      #     git config user.email "intjborj@gmail.com"
      #     git add .
      #     git commit -m "Updating api version to ${{ needs.build.outputs.version }}"
      #     git push -u origin main
      - name: Update ArgoCD Manifest
        run: |
          cd dev
          BUILD_VERSION="${{ needs.build.outputs.version }}"
          echo $BUILD_VERSION
          sed -i "s|intjborj/api-demo:\(.*\)|intjborj/api-demo:${BUILD_VERSION}|" api-demo.yaml
          cat api-demo.yaml
          git config --global user.name "api deployment"
          git config user.email "intjborj@gmail.com"
          git add .
          git commit -m "Updating api version to $BUILD_VERSION"
          git push -u origin main

          
