name: Acebook FRONT BETA

on: 
  push:
    #  branches: [ staging ]
     branches: [ staging-beta ]
#     paths:
#       - 'api/**' 
jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node-version: [16.13.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: front
  
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: docker build nodejs
      run: |
       docker build -f front/Dockerfile.beta ./front -t acemcbmis/acebook-front-beta:${{ steps.package-version.outputs.current-version}}badp
    - name: docker push
      run: |
        docker push acemcbmis/acebook-front-beta:${{ steps.package-version.outputs.current-version}}badp
